import { BANNER_FOLDER, GALLERY_FOLDER, SECTION_FOLDER } from './constants';

const banners = [`${BANNER_FOLDER}/1.jpg`];

const gallery = [
  `${GALLERY_FOLDER}/1.jpg`,
  `${GALLERY_FOLDER}/2.jpg`,
  `${GALLERY_FOLDER}/3.jpg`,
  `${GALLERY_FOLDER}/4.jpg`,
  `${GALLERY_FOLDER}/5.jpg`,
  `${GALLERY_FOLDER}/6.jpg`,
  `${GALLERY_FOLDER}/7.jpg`,
  `${GALLERY_FOLDER}/8.jpg`,
  `${GALLERY_FOLDER}/9.jpg`,
  `${GALLERY_FOLDER}/10.jpg`
];

const sections = [
  {
    title: 'Journalism',
    image: `${SECTION_FOLDER}/journalism.jpg`,
  },

  {
    title: 'Handicraft',
    image: `${SECTION_FOLDER}/handicraft.jpg`,
  },

  {
    title: 'Computer',
    image: `${SECTION_FOLDER}/computer.png`,
  },

  {
    title: 'Beautician',
    image: `${SECTION_FOLDER}/beautician.jpg`,
  }
];

const content = {
  heading: 'WELCOME TO PUBLIC JUSTICE INSTITUTION',
  description:
    'Department of Consumer Affairs is one of the two Departments under the Ministry of Consumer Affairs, Food &amp; Public Distribution. It was constituted as a separate Department in June 1997 as it was considered necessary to have a separate Department to give a fillip to the nascent consumer movement in the country.',
  button: {
    text: 'More'
  },
  about: [
    'The institution is approved by Ministry of Consumer Affairs, Food & Public Distribution, Govt. of India Under The Emblem and Name (PIU) Act - 1950 wide Approval Letter Number - 23/14/2009 IT, Dated - 23/09/2010 Application to be sent by Govt. of Delhi wide Application Number - S/RFS/2607 Dated On - 23/02/2010',
    'Letter Number - P2E/ 10,500 Issued by Honble President of India Sectt. Govt. of India, Wide a Direction for Issued the Approval of LOK NIYAY SANSTHAN',
    'Letter Number - PMO ID No - 1/3/2010-PMP1/120855 Dated On - 19/02/2010 Issued by Honble Prime Minister Office, Govt. of India, wide a Direction for issued the Approval of LOK NIYAY SANSTHAN',
    'Letter Number - M- 11014/8/2010-CDN Issued by Honble Ministry of HRD, Deptt. of Higher Education, Govt. of India, Wide a Direction to Approval of LOK NIYAY SANSTHAN'
  ],
  biologueHeading:
    'THE INSTITUTION WILL WORK IN ALL OUR INDIA AND INSTITUTIONAL WORK IN AS UNDER: -',
  biologues: [
    'To provide sound education to children of all communities irrespective of their race, religions, cast or creed in general and to prepare them to become mature and responsible citizens of the country through the all round physical, intellectual, academic, mental and spiritual development based on values derived from the life.',
    'To start establish, run take over, or manage and maintain mandir and to provide all the facilities.',
    'To open, found, establish, promote set-up, run, maintain, assist, finance, support and/or aid and help in the setting up different kinds mandir.',
    'To arrange and manage the training institution in Typing, Short- Hand Computer Information Technology, Fine Arts, Craft, Music, Painting, Modeling, Cutting & Tailoring, Yoga, Physical Educational and other social activities of Awareness Programs, Adult Education Classes, Lectures, Essay Competitions Exhibitions, Symposium, Cultural Programs, Press Conference and Seminars.',
    'To establish, run, maintain and grant aid in cash or kinds to Advance Technical Education Colleges including Engineering & Diploma College, Management Education Institute, Computer Science & Engineering Institutes, Teacher Training & Specialized Studies & Research Institutes, Teacher Training & Specialized Studies & research Institutes, Teacher Training & Specialized Education for B.E./ B.Tech./ B.Arc/ MBA/ M.Ed/ N.I.T. Courses & other related courses to the student according to rules and regulations of A.I.C.T.E. & State Government.',
    'To make necessary changes and widen the prevalent school educational system and to caster to the numerous new vacations that are being created increasingly with the explosion in the areas of science and technology.',
    'To Adopt system in the school education that would promote and stress leaving body doing through the information of science laboratories and workshops in all the areas of learning.',
    'To develop the establish such out of school activity centers for the children on the underprivileged class of society. Where they could have the benefits and joy of participating in sports, game artistic activities like painting, elections, participate in excursions, educational trips and such other activities.',
    'To establish reading rooms libraries to the members of the society students and general public.',
    'To start various kinds of training courses like - Teacher, Training, Nurses Training, Technical and Non-Technical Course, Laboratory Assistant, Hospital Education Center Cum Clinics, Maternity Homes, Child Care Centers and such other Institutes (after I getting the permissions and/or affiliation from the competent authority/authorities, if it is required) for the solution of problem of un-employment amongst the young generation use of general public.',
    'To establish, run, maintain, manage and control the various schools/colleges, Training Institution/Courses like, Medical, Dental, Para Medical, Ayurvedic, Homeopathic Naturopathy, Pharmacy, Nursing, Laboratory, Occupational Therapy, Dietician, Beautician, Acupuncture and Acupressure Therapy etc. (after getting proper permission from the competent authority it is required).',
    'To carry out research and training in education to enhance the quality ad method of teaching and to establish, carry on training institutions for the benefits of the community and to equip and manage such institutions.',
    'To promote literacy, cultural and other social activities of Awareness Programs, Adult Education Classes, Lectures, Essay Competitions Exhibitions, Symposium, Cultural Programs, Press Conferences snd Seminars.',
    'To promote food, clothing, medical aid, stationery, transportation, libraries, laboratories, reading room, hostel play ground swimming pool and other required facilities to the students and also to the members of the society.',
    'To establish and manage various lands of Educational, Vocational, Industrial Agricultural, Research and Training Institutions to introduce and develop the professional courses and also to arrange/provide all kinds of educational facilities to the students, scholars, trainees and to other needy candidate.',
    'To institute scholarships and help to deserving students and to institute and award prizes in recognition of excellence and academic performance of students.',
    'To meet traveling, boarding and lodging expenses for the students going aboard for higher education and also help them in all possible ways.',
    'To promote fine art, crafts among the public including establishment and maintenance of Shilpa - Shikshalyas, Kala - Kendras (relating to music, dance & modeling) etc.',
    'To follow the ideology of Great Men and National Leaders who sacrificed their lives for the causes of depressed, SC & ST backward Classes, Minority Groups and for other needy people.',
    'To provide free/confessional education to the poor, helpless and needy children/students.',
    'To revive and encourage the Indian Art, Cultural and Literature.',
    'To make efforts to spread education especially Punjabi, Haryanvi literature.',
    'To promote the adventure among the youth.',
    'To arrange and organize "LANGER" on the different occasions as and when the Governing Body of the society may decide from time to time in the Governing Body Meeting called for this purpose.',
    'To arrange tours and trips at the historical and tourist places (time to time) and provide all possible facilities to the member like transportation, breakfast, lunch, dinner, temporary, shelters etc.',
    'To create a forum for Senior Citizens where they can exchange their various views and experience, which may be, make available to younger generation.',
    'To help people in the pre-retirement stage to prepare them for life-after retirement from service.',
    'To consolidate people to build free strong, untied nad fully developed INDIA in social welfare.',
    'To foster Social spirit among people to build national character.',
    "To foster the ideals of loyal and efficient service among the people of india and to encourage they're all round social advancement.",
    'To promote safeguard and advance the social, educational interest of the people of India.',
    'To arrange periodical meetings to exchange information on various latest development in the country.',
    'To put the view points of Indian intellectuals related to human man kind and the country through press and conferences, seminars, workshops and get together for consideration by the seminaries, workshop and get together for consideration by the seminars, workshops and get together for consideration by the people and the Government in the capacity of advisor only.',
    'To organize trekking, Mountaineering expedition and other allied sports activities related Mountain, Desert and Coastal terrains.',
    'To study the living and customs of the dwellers of rural & J J Clusters.',
    'To organize group marriage programmer form time to time.',
    'To establish, maintain or grant aid for the establishment maintenance of wells, tube-wells, tanks, and water reservoirs, trees and also to make the constructions & maintenance of Paths, Roads, Khadanja, Bridges, Parks, Sewerage and other buildings and institution which does the general public use.',
    'To educate the people and organize various kinds of awareness program/activities regarding Consumer Protection Laws and rights of the public in the connection.',
    'To help poor and indigent persons in marriage of their sons and daughters by way of cash donation of otherwise and to distribute clothes, food and other necessaries of daily life amongst the poor, orphan and indigent persons.',
    'To make arrangement for mobile emergency Van/Ambulance for the victims of road accidents to provide help to pregnant ladies to shift them to near by hospital also to provide assistance to the old people for thr emergency.',
    'To provide nursing aid to the needy people especially for the old age men and women, orphan, ill etc.',
    'To arrange and organize EYE and BLOOD donation camp all over in india.',
    "To conduct training and research programs for pollution control (in-water, air, soil, earth, atmosphere). polluted diseases and to maintain / develop and also protect the Herd's Forest, Environments, Species of the Animals, Birds, Wild Life and other Natural Gifts helping to so support the preservation of Environment widows, old men and women, poor, beggars, handicapped, blinds, deaf, dumb, mentally retarded and for other needy people.",
    'To give provide and/or render monetary and/or other help and assistance for the relief of the persons and animals affected by natural and other calamities such as flood, true, famine, cyclone, earth quake, storm, accidents, pestilence, drought, epidemic, unbearable contributions, to institution, establishment, centers or persons doing relief work on such occasions.',
    'To approach and to encourage the people to donate Blankets, Rugs, Woolen/Cotton/Silk or other varieties of cloths or other articles of necessary and also provide food, cloth, shelter, (temporary/permanent), medicines, and other required facilities to the people who have faced the natural calamity and/or the disaster.',
    'To make best effort for protection, promotion, the advancement and start rehabilitation center & school for women, children, old aged, handicapped orphans, widows, destitute and mentally retarded persons, beggars, blinds, and needy people of the society.',
    'To carry on community development programmers/activities and also contraction and development the Community Hall, Barat Ghar Dharamshalas, Pio, Sulb Sochalayas Old-Aged Home, Mobile Health Van, Health Care Centers, Charitable Dispensaries, Hospital, Libraries, Reading Room, Play Ground Stadium (both open and indoor) Yoga Training Centers, Anganwari Balwari, Studios, Drama Stage and other training and research institute for the attainment of the Aims and projects of the society (after allotment of land from competent authority if required).',
    'To promote the interest of people in Environment, Sense of Integration, Self Employment, Family Planning, sanitation section by making audio Visual, Tele Films, T.V. Serial and documentary on various aspects of culture music, craft, environment, health, sports and palace of social integration. The society will also organize the stage plays, musical concert, seminars and variety programmers on special occasions.',
    'To establish & run orphanage and leprosy Asylum in different parts of the country and abroad and also provide welfare service.',
    'Encourage Games/ Sport/ Yoga/ Gymnastic/ Judo/ Hockey/ Footballs, Cricket and other games of the improvement of health amongst youth and children on the whole by providing play ground, sports clubs indoor stadium, training center and also organize the tournaments Yoga Sport competition on block, district, stage Naional and International level.',
    'To prepare the awareness generation kits, poster, banners, audio, video cassettes, Nukkad Natak, Puppet Shows, Skits Documentary etc. regarding various social issues and for the attainment of the aims and objects of the society.',
    'To establish and maintain institutions for the handicapped disable blind, poor, and child labour SC & ST, BC, OBC, classes and other needy persond like vacations training in vacations of house hold industries, semi-skilled jobs for self employment and to provide food, clothing, medical and transpirations, libraries, reading rooms, hotels, playgrounds, swimming pool and other required facilities to be boys/ girls and to the members of the society.',
    'To provide and helps/assistance to the physically handicapped people/children in respects of artificial limbs and give him vocational training on different technical non-technical professional/industrial and on the other subject/fields which will make them independent.',
    'To establish and run orphanage centers creches for thr children and working women and hostels for working women.',
    'To take over manage, establish, administer, carry on conduct, develop, improve all kinds of educational social, scientific, technical, commercial and cultural work and activities of all kinds for the benefits of entire community.',
    'To run, open found establish, promote, support, finance and/or help the charitable educational industrial cultural, technical/non-technical, vocational, Ayuvedic pharmacy, Yoga training institutes, Animals and Birds Hospital, research and manufacture of herbal medicines for thr community.',
    'To work for the eradication of illiteracy among the public in particular, among the rural, Poor slums dwellers, by running adult classes for both men and women.',
    'To provide educational help of the all sorts, academic, competitive, professional, technical and commercial for assisting the unemployed youth of the entire community in securing jobs for leading and honorable life in the society.',
    'To run books banks, finishing school, coaching classes for competitive examination, to guide young and qualified people to take up various professional jobs, both technical and others.',
    'To provide residential/hostels, accommodation for consideration and to educate trained and assist financially or otherwise in the education and training of teachers, social workers staff, student and other persons for the society, including SC, ST, BC, OBC, and other disciplines on different subjects realign education.',
    'To carry out programmers and to establish centers to educate the people about environment to establish maintain and to take over institute conducting courses and imparting necessary training to protect and manage the environment.',
    'To educate the entire community regarding the importance and benefits of family planning for overall progress and development of the country.',
    'To establish laboratories, workshops, libraries, research, establishments, study centers art &amp; cultural centers, social centers etc.',
    'To promote fellowship and to foster spirit of cooperation unity and fraternity among members through social, cultural, educational and other means.',
    'To arrange periodical social gathering and cultural programmers.',
    'To promote conscious educational/welfare and treatment programs to control the AIDS, Cancer, Diabetes, Leprosy, Tuberculosis, Syphilis, Heart, Skin and other Diseases.',
    'To establish and promote training, welfare, and rehabilitation for Blindness, Deafness, Dumbness, Lunatic, Leprosy, Physical, &amp; any other Disability Patients.',
    'To provide legal, medical, aid, social, economic, help an assistance to the needy people.',
    'To approach to the competent court/courts to safeguard the rights of the general public and for the public interests form time to time as the society may deem fit and proper.',
    'To receive loans, financial and non-financial from Govt, Non-Govt, Organization, International, Agencies, Banks and any other legal entity or individual.',
    'To engage, employ or hire appropriate staff, workers, legal or other professionals, attorneys, managers, and agents, for the works and furtherance of the aims and objects of the society and to pay they wages, salaries, stipends, or fees.',
    'To accepts donations, grants, presents, gifts and other offerings in the shape of moveable and/or immovable properties for the attainment of the aims and objects of the society.',
    'To borrow or receive money &#40;with interest or without interest&#41; and upon such terms and condition as are approved by the Government body of the society.',
    'To raise funds and resources for the attainment of any of aims and objects of the society by all lawful means including investment of the funds, donation, fund-raising campaigns, cultural programs, sale of literature, property development, rent form the building etc.',
    'To Operate the Legal Proceedings against the Govt. Abbacies is regard of bribery and corruption. To invest the moneys of the society not immediately required, in mutual funds, UTI, Securities or Deposits as are permitted by the law for the time being in force.',
    'To purchase/acquire the land and/or the building in the name of the society for the different establishments and for fulfillment of the aims and object of the society.',
    'To erect, construct, alter, maintain, sell, lease, mortgage, transfer, improve, manage and/or develop all or a part of the property of the building of the above society necessary or convenient for the purpose the attainment of the aims &amp; objects of the society.',
    'To purchase construct new building, hostel or structures and/or modify, renovate, re-build or alter or such existing building as may be necessary for the purpose of the society and to maintain such buildings in good condition.',
    'To purchase or hire permanently or temporarily any vehicle or vehicles for transportation of the students &amp; concerned in good condition.',
    'To assist and co-operator the other association, trusts and the various N.G.O. whose aims are same like this society.',
    'To do such other things/act/activator which are necessary and which may be incidental or conductive to the attainment of any or the aims and object of the society.',
    'To make survey for collection of data and provide for free consultancy services for the attainment of any object of the society.',
    "To collect notices, notification, policies information's from the Govt, Semi-Govt, N.G.O.'s and other National, International Agencies and provide to general public.",
    'To aware the people about the newly and amended laws time to time.',
    'To approach to the competent court/courts to safeguard the rights of the general public and for the public interests form time to time as the society may deem fit and proper.',
    'The society will invest its money and founds according to the section 11&#40;5&#41; of the income Tax Act 1961.',
    'ALL THE ACTS/ACTIVITIES/PROGRAMS SHALL BE NON-PROFITABLE AND SHALL BE DONE ON NO PROFIT - NO LOSS BASES.',
    'To run educational vocational training and in come generating programmer and other social justice &amp; development programmer for masses especially for SC, ST, BC, OBC, Minorities child, women, aged and disability sector.',
    'To take all initiatives, programmer, schemes, researches in social defense, Alcohol and drug demand reduction, Animal Welfare, Wild Life, Environment &amp; Forest Agricultural, Horticultural, Road Safety &amp; High Ways, Rural Development, Handicrafts, Herbs, Ayurved Ground Water, Water Harvesting, Drinking Water Child Labour, Women Labour, Sports Youth Activities &amp; Training Sarv Sikhsha Abhiyan and Disability Sector.',
    'To apply and get registered under Sec 80-G, of the Income Tax Act.',
    'To arrange and organize Exhibitions, Training and Research programs on the subjects/matters relating to the villages and people belongs to the rural areas of the country and also start different Integrated village Development programs all over in INDIA.',
    'To Promote the interest of people in environment, sense of integration, self-employment and sanitation etc.',
    'To publish Books, Charts, Illustrations, Journals, Magazines, Periodicals, News Letters/Posters and other publications the different subjects and in different language for the promotion of above aims and objects of the above society.',
    'To conduct research in education and other discipline with difference subject relating to education.',
    'All the incomes, earnings, moveable/immovable properties of the society shall be solely utilized and applied towards the promotion of its aims and object only as set forth in the memorandum of the society and no profit on thereof shall be paid or transferred directly or in directly by way of dividends bonus, profits or in any manner whosoever to the present or past members of the society or to any person claiming through anyone or more of the present or the past members "no members of the society shall have any personal claim on any movable or immovable properties of the society or make any profits, whatsoever, by virtue of this membership".',
    'To secure the rights of the persons of SC/ST/OBC/BC/Minority communities and to get them received the certificates by the Govt.',
    'To grant the marriage certificate to the poor family girls after getting married by the attempts of the institution.',
    'To assist the police &amp; other forces against the terrorists by forming &amp; granting training an important group and to oppose the terrorism rigidly.',
    'To assist the society through the institution regarding passport Voter ID Card, PAN Card, Ration Card and other social activities and to asks the govt. for the actions against corrupt workers.',
    'To assist the citizens and intend the public to assist the suffered people at the time of emergency &amp; havocs',
    'To assist the public through the regional S.D.M/ District Commissioner to regarding the problems of Date of Birth &amp; Death Certificate.',
    'To request the govt. through the institution to sort out the problems of Water, Electricity, Road, Banquet Hall, Govt. Dispensary.',
    'To assist the people regarding all the pension, handicapped pension widow pension, physically &amp; mentally handicapped pension and to enter the complete details of such pension in the register of the institution.',
    'To assist the people regarding all the activities of social welfare department and to send the documents to the offices self to make the people free from the difficulties.',
    'To get the national flag unfurled by the state or national level leaders or senior Govt. Officers at the time of Republic Day, Independence Day and other National Festivals.',
    'To attest the photocopies of Govt. or Non Govt. Documents by seeing their original copies.',
    'To get the police verification of the person being appointed to the institution who wish to serve the society.',
    'To provide the written information to the ACP/DCP/CP/ &amp; other Senior Officers through the institutional letter about the meeting held by the institution regarding the social/official &amp; others.',
    '*NOT AVAILABLE FOR EVERYONE',
    'To hold the social conference to sort out the different social problems through the institutions and to get the culprits punished hard by complify the proper just.',
    'To raise the collective speeches against the bad activities being faced by the ladies and to assist them fully by asking for the Govt. to have hard stamps to act against guilty persons.',
    'To raise the collective speeches against the attempts to disobey the national cultural displaying programs and to ask for the canceling certificates of wrong programs.',
    'To provoke the people to secure the human rights and to get the complaints lodges to the concerned offices against the person disobeying at the human rights.',
    'To get the people approached to the laws ot RTI 2005 &amp; others formed by the Govt.',
    'To obey the orders of senior leaders of the country and to respect them and to put up the public problems before them.',
    'To grant the certificates to reporters after granting the proper knowledge of writing by the institution.',
    'To attempt to start multipurpose exercise halls, health clubs and child progress centres.',
    'To construct residential schools snd hostels for weak category students.',
    'To attempt to open center at different places for thr prevention of leprosy etc. and institutional family welfare.',
    'The institution will organize the branches for the welfare of society and its working commetee at national level, state level, district level, ward-level, block-level.',
    'The institutional will keep up the programmes of blood-donations, eye donation and health camps for the poor and helpless children woman and people form time to time',
    'To distribute the encouraging certificate and grant the training in games &amp; sports to the poor children by the institution.',
    'To keep up the alert programme for the prevention of population increasing from time to time.',
    'The institution will work for the rights of labours and woman working in houses.',
    'To develop the institutional all around with the help of Govt. and foreign aids.',
    'To help the poor, backwards in the disputers of police station. Tehsil. court and offer legal advices through proper advocates free of costs.',
    'The institution will develop banks for the progress of society through the Govt. &amp; Non-Govt loans.',
    'To aware society with the ill deeds and to establish drug free society.',
    'To arrange the rest houses for the old people.',
    'To institution will arrange the cheap cloth &amp; food distribution in summer &amp; winter for the poor.',
    'The institution will work to join the tribes and moving here &amp; there people to the principal streams of the country.',
    'To act against dowry and non-human activities against the poor children.',
    'To attempt, to awake the society by rallies, pradarshan dharnas &amp; strikes.',
    'To deprive the society from superstitions and to make aware.',
    'The institution will be ahead always to grant the aid concerned to the improvement of environment for the progress of birds, animals and other living creatives.',
    'The people will be made aware through the programmes of membership of the institution in villages, cities, districts, blocks.',
    'To attempt to establish the residential villages at Govt. expenses for the poor &amp; SC/ST/OBC/BC/',
    'The institution will work and raise voices against the differentiation tyrannical activities by the police &amp; other govt. department.',
    'The institution will cooperate particularly for the welfare of blinds &amp; handicaps and to help in emergency and casual accidents',
    'To get the poor children admitted in govt. or non-govt. school.',
    'To help the children &amp; woman for the incomplete progress by organizing woman &amp; children federation the govt. &amp; non govt. aid.',
    'Raising collective voice and demand justice from the government against injustice being done with poor labours.',
    'Awaking for presaging on goods on appropriate price in fainer of consumers. And all so raise voice against shopkeepers sale in goods against in the violation of the set rules.',
    'Becoming member of the social society run by government and refer public grievances and appropriate schemes to the government for the welfare and benefit of consumers [public] to the public.',
    'Encroachment and illegals profession of the government about the non tax paries emnpairsener being enjoined unlimited wealth with them.',
    'Awaking the public adopting different religions sex cast, sub cast, extra in strengthening to the integrality of the nation.',
    'Preparing list of educated and uneducated unemployed persons and enable help them to get employment according to their qualification.',
    'To awaken the public against the unqualified and lowly educated so called doctors and others and demand to the government to take action against them.',
    'Bringing the traffic rules to the notice of public through our society and also awaking to follow the traffic police rule.',
    'To arrange singing, dancing and musical programmes to the public and also giving such programme and telecast on T.V. through the society.',
    'To advancing the educational at system via Hindi, English, Urdu and Arbi medium establish school and provide the complete facility to poor children and provide respects to the parents of poor children.',
    'To awaken the people on behalf of the organization form through Newspapers/Maganoze/T.V. programmes about the planning of yhe government and approach with the problems of the public to the govt.',
    'To awaken the people about is respect of the training for employment and to discourage the people from thr illegal work and awaken to proper nourishment.',
    'Request for the construction of the bus terminals to the State Govt. and Central Govt.',
    'Make request to the Govt. to the proper sanitation and purify the shivers and ponds through machines.',
    'To make request and demands to the Govt. to cancel the license of those film theater where obscene films and programs picturize.',
    'To make complaints to the state and central Govt. in those states where pension is not provide to the old handicapped mentally imbalanced persons and widows.',
    'To make the list of those person who comes under the poverty line and provide them BPL Ration Card etc through Govt. and inform to the state &amp; central Govt. about the corruption in the offices and demand for proper the proceedings.',
    'To provide proper emigration through tube well to the poor cultivators and also provide them other helps through proper facilities through Govt. plans.',
    'To abolish the illegal works through the aid of the police against the gambling and drinking i.e., Wine, Gaanja, Drugs, Sulpha, Chars, Afim, and other for proper proceeding through Govt.',
    'To make efforts to work out on the plans of the Govt. and also make the efforts to dispose of the plans of State and Central Govt.',
    'To make request to improve and renovate the residence of the poor people by the State and Central Govt.',
    'To facilitate the people through animals husbandry through various &amp; scheme of Govt.',
    'To request the Govt. to make a list of old building and re-construct them.',
    'To provide the licenses batch and other facilities to the drivers through the State &amp; Central Govt. and to give them employment.',
    'To provide help to the persons of different professions and businessmen &amp; other people and make them aware about two rights and rules of the Govt.',
    'To provide the goods on cheaper price to the people and to inform. the Govt. about the corruption in the Govt. shops.',
    'To demand the strict legal proceeding against the illegality of operation of tube wells land Barat Ghar, Hospitals, Schools and Police Station to the Govt. and corruption branch.',
    'To request the govt. to provide the certificate to those organization which work out for the welfare of the govt. to officials for their progress.',
    'To provide the right to the cultivator and to demands for financial facility to them.',
    'To provide the facility of the letter boxes for the improvement of the problems of the people in which people can drop the letters at any time containing the problems on which the president of the organisation Mr. Shah Alam himself take himself'
  ]
};

export {
  banners,
  gallery,
  sections,
  content,
};
